# See: https://github.com/Kapernikov/skaffold-helm-tutorial/
apiVersion: skaffold/v3
kind: Config
metadata:
  name: cast
build:
  local:
    push: false
  artifacts:
    -
      image: collector
      context: .
      platforms:
        - "linux/amd64"
      docker:
        dockerfile: collector/Dockerfile
    -
      image: ui
      context: ui
      platforms:
        - "linux/amd64"
      docker:
        dockerfile: ui/Dockerfile
deploy:
  helm:
    releases:
    - name: cast
      chartPath: k8s/helm/cast
      namespace: cast
      createNamespace: true
      setValues:
        postgresql.auth.password: "dev-password"
        "imagePullSecrets[0].name": "regcred"
      setValueTemplates:
        collector.image.repository: "{{ .IMAGE_REPO }}"
        collector.image.tag: "{{ .IMAGE_TAG }}"

        ui.image.repository: "{{ .IMAGE_REPO2 }}"
        ui.image.tag: "{{ .IMAGE_TAG2 }}"
    - name: httpbin
      namespace: cast
      remoteChart: https://matheusfm.dev/charts/httpbin-0.1.1.tgz
    hooks:
      after:
        - host:
            command: ["sh","-c", "./scripts/kubeshark-tap-with-data.sh http://httpbin.cast.svc.cluster.local"]

portForward:
  - resourceType: service
    resourceName: cast-service
    port: 80
    localPort: 8000

  - resourceType: service
    resourceName: cast-postgresql
    port: 5432
    localPort: 5432

  - resourceType: service
    resourceName: httpbin
    port: 80
    localPort: 8080

profiles:
  # Deploy the chart in headless mode
  - name: headless
    patches:
      - op: remove
        path: /build/artifacts/1
      - op: add
        path: /deploy/helm/releases/0/setValues/headless
        value: true
      - op: remove
        path: /portForward/0
