# Copyright 2022 Corsha.
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for cast.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []

postgresql:
  auth:
    username: cast
    database: cast
  primary:
    annotations:
      container.seccomp.security.alpha.kubernetes.io/pod: runtime/default
      container.apparmor.security.beta.kubernetes.io/pod: 'docker-default'
    containerSecurityContext:
      enabled: true
      capabilities:
        drop:
          - ALL
    extendedConfiguration: |
      password_encryption=scram-sha-256
    initdb:
      scriptsConfigMap: cast-db-init
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      annotations: {}
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi

plugins:
  kubesec:
    enabled: true
    serverImage: docker.io/kubesec/kubesec:v2
    schedule: "0 * * * *" # Default: Hourly
    serviceAccount:
      role:
        # Create the role from our chart, on by default.
        #
        # If you turn install off, you must provide your own
        # role and rolebinding for the serviceaccount.
        install: true
        # The name of the created role. If you turn "install"
        # off, name your custom role here.
        name: kubesec-read-role
      account:
        # Create the serviceaccount from our chart, on by default
        install: true
        # The name of the created serviceaccount. If you turn "install"
        # off, name your custom serviceaccount here.
        name: kubesec-serviceaccount
    env:
      PGPORT: "5432"
    image:
      tag: ""
      repository: ghcr.io/corshatech/cast/plugins/kubesec

collector:
  env:
    PGPORT: "5432"
    KUBESHARK_HUB_URL: "http://kubeshark-hub.kubeshark.svc.cluster.local"

  image:
    tag: ""
    repository: ghcr.io/corshatech/cast/collector

ui:
  env:
    PGPORT: "5432"
  image:
    tag: ""
    repository: ghcr.io/corshatech/cast/ui

# Run CAST in headless mode which disables the UI
headless: false
