{{ if .Values.plugins.kubesec.enabled }}
{{ if .Values.plugins.kubesec.serviceAccount.account.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.plugins.kubesec.serviceAccount.account.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: cast-plugin-kubesec
{{ end }}
{{ end }}
