{{ if .Values.plugins.kubesec.enabled }}
{{ if .Values.plugins.kubesec.serviceAccount.role.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.plugins.kubesec.serviceAccount.role.name | quote }}
  labels:
    app: cast-plugin-kubesec
rules:
- apiGroups: [""]
  resources:
    - configmaps
    - daemonsets
    - deployments
    - endpoints
    - events
    - ingress
    - ingress
    - jobs
    - persistentvolumeclaims
    - persistentvolumes
    - pods
    - replicasets
    - serviceaccounts
    - services
    - statefulsets
  verbs:
    - get
    - watch
    - list
{{ end }}
{{ end }}
