apiVersion: v1
kind: Secret
type: generic
metadata:
  name: cast-db-init-secret
  labels:
    app.kubernetes.io/component: pgsql
data:
  init.sh: {{ b64enc "PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres cast -c 'create extension postgis;'" }}
