on:
  pull_request:
    branches:
      - main

name: Code Coverage

jobs:
  build:
    name: code-coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install node dependencies
        working-directory: ./ui
        run: npm install

      - name: Generate node coverage report
        working-directory: ./ui
        run: npm run test:coverage

      - name: Generate node coverage badge
        uses: tj-actions/coverage-badge-js@v1.3
        with:
          report_path: ui/coverage/coverage-summary.json
          output_path: docs/badge.svg

      - name: Generate go coverage report
        run: |
          make test
          go tool cover -func=coverage.out -o=coverage.out
      
      - name: Set coverage badges
        run: |
          GO_COV=`sed -n -e 's/total:\t(statements)\t\(.*\)%/\1/p' < coverage.out`
          GO_COLOR=red
          echo $GO_COLOR
          if (( $(echo "$GO_COV 85.0" | awk '{print ($1 > $2)}') )); then GO_COLOR=green; elif (( $(echo "$GO_COV 70.0" | awk '{print ($1 > $2)}') )); then GO_COLOR=yellow; fi
          sed -i -r "s/Go%20Coverage-\(.*\)%25-\(.*\)/Go%20Coverage-$GO_COV%25-$GO_COLOR)/" README.md
          NODE_COV=`cat docs/badge.svg | grep -Eo '[0-9\.]*%' | head -1 | sed 's/%//'`
          NODE_COLOR=red
          if (( $(echo "$NODE_COV 85.0" | awk '{print ($1 > $2)}') )); then NODE_COLOR=green; elif (( $(echo "$NODE_COV 70.0" | awk '{print ($1 > $2)}') )); then NODE_COLOR=yellow; fi
          sed -i -r "s/Node%20Coverage-\(.*\)%\(.*\)/Node%20Coverage-$NODE_COV%$NODE_COLOR)/" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md docs/badge.svg
          git commit -m "chore: Updated coverage badge."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}
