on:
  pull_request:
    branches:
      - main

name: Code Coverage

jobs:
  build:
    name: code-coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install node dependencies
        working-directory: ./ui
        run: npm install

      - name: Generate node coverage report
        working-directory: ./ui
        run: npm run test:coverage

      - name: Generate node coverage badge
        uses: tj-actions/coverage-badge-js@v1.3
        with:
          report_path: ui/coverage/coverage-summary.json
          output_path: docs/badge.svg

      - name: Generate go coverage report
        run: |
          make test
          go install github.com/axw/gocov/gocov@v1.1.0

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 6171d8bd9b3c3a65ec23588397d36a5630bc1a74561eec25349639794655bcdc
        with:
          coverageCommand: gocov convert coverage.out > c.out
          coverageLocations: |
            ${{github.workspace}}/c.out:gocov
            ${{github.workspace}}/ui/coverage/*.lcov:lcov

