on:
  push:
  pull_request:
    branches:
      - main

name: Linter

permissions:
  contents: read

jobs:
  golint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Go lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m

  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs "k8s/helm/cast" --all --target-branch ${{ github.event.repository.default_branch }}
